.TH TP 1 Sept98 RSUG
.SH NAME 
.B tp
\-  send alpha-numeric pages, using text page protocol
.SH SYNOPSIS
.B tp 
[
.I options
] 
.I user
.br
.B tp 
[
.I options
] 
.B \-m 
.I user
\&.\|.\|.
.br
.B tp 
[
.I options
]
.I user 
.I message
...
.br
.SH DESCRIPTION
.B tp
queues alpha-numeric pages to a TPP server, by default the hostname
.RB `` tpp ''.
The server,
.BR tppd (8),
accepts page requests and later delivers the data to a paging service
provider.
.LP
If
.B tp
is invoked with only one command line argument or with
.BR \-m ,
all command line arguments are interpreted as
.IR user s
and the message is given on stdin, terminated by EOF or ``.'' on a line
by itself.  Otherwise,
.B tp
interprets it's first argument as a
.IR user ,
and the remaining command line arguments as the message.  Note: The
shell interprets the command line arguments, e.g.  !  ? * [ ].
Characters that are special to the shell must be escaped or quoted.
.SH OPTIONS
.TP 20
.B \-V
displays the version of
.B tp
and exits.
.TP 20
.B \-v
display the protocol exchange with the TPP server.
.TP 20
.BI \-h\  hostname
specifies the TPP server, by default ``tpp''.
.TP 20
.BI \-p\  port
specifies TPP port, by default 6661.
.TP 20
.B \-m
interprets command line arguments as multiple users and reads messages
on stdin, ending with EOF or a ``.''.
.TP 20
.B \-q
quiet mode, displays only errors.
.SH EXAMPLES
In this example, user ``bob'' will recieve the message ``you
suck, bob!'':
.sp
.RS
.nf
	example% tp bob you suck, bob\\!
	Page queued on tpp.
	example%
.fi
.RE
.sp
Note that the ``!'' must be escaped in many shells.
.LP
In the following example, users ``bob'' and ``betty'' will receive the message
``you are both big losers, bob and betty!'':
.sp
.RS
.nf
	example% tp -m bob betty
	you are both big losers, bob and betty!
	.
	Page queued on tpp.
	example%
.fi
.RE
.sp
Since the ``!'' is taken as stdin, no escape is necessary.
.SH SEE ALSO
.BR tppd (8).
